"""Tests für actions/reminder.py — Eingabevalidierung, Skript-Erzeugung, Dispatch je OS."""
from datetime import datetime, timedelta

import pytest

from actions import reminder as rm


@pytest.fixture(autouse=True)
def tmp_scripts_dir(tmp_path, monkeypatch):
    monkeypatch.setattr(rm, "_scripts_dir", lambda: tmp_path)
    yield


def _future() -> tuple[str, str]:
    dt = datetime.now() + timedelta(days=1)
    return dt.strftime("%Y-%m-%d"), dt.strftime("%H:%M")


# ── Eingabevalidierung ────────────────────────────────────────────────────────
def test_missing_date_or_time_is_rejected():
    date, time_ = _future()
    assert "need both a date and a time" in rm.reminder({"time": time_, "message": "x"})
    assert "need both a date and a time" in rm.reminder({"date": date, "message": "x"})


def test_unparseable_date_or_time_is_rejected():
    result = rm.reminder({"date": "nicht-ein-datum", "time": "25:99", "message": "x"})
    assert "couldn't parse" in result.lower()


def test_time_in_the_past_is_rejected():
    result = rm.reminder({"date": "2020-01-01", "time": "10:00", "message": "x"})
    assert "already passed" in result


# ── _sanitise ────────────────────────────────────────────────────────────────
def test_sanitise_strips_quotes_backslashes_and_newlines():
    dirty = 'sag "hallo"\nund\r\\weiter'
    assert '"' not in rm._sanitise(dirty)
    assert "\\" not in rm._sanitise(dirty)
    assert "\n" not in rm._sanitise(dirty)


def test_sanitise_truncates_to_max_len():
    assert len(rm._sanitise("x" * 500, max_len=50)) == 50


# ── _write_notify_script ──────────────────────────────────────────────────────
@pytest.mark.parametrize("os_name", ["windows", "mac", "linux"])
def test_write_notify_script_embeds_message_and_is_owner_only(os_name):
    path = rm._write_notify_script("task1", "Kaffee kochen", os_name)
    assert path.exists()
    content = path.read_text(encoding="utf-8")
    assert "Kaffee kochen" in content
    assert "Auto-generated by MIA reminder" in content
    assert "unlink(missing_ok=True)" in content
    assert oct(path.stat().st_mode)[-3:] == "600"


# ── reminder(): erfolgreicher Ablauf, mit gemocktem OS-Scheduler ─────────────
def test_reminder_success_calls_linux_scheduler_and_reports_friendly_time(monkeypatch):
    monkeypatch.setattr(rm, "_get_os", lambda: "linux")
    called = {}

    def fake_schedule(target_dt, task_name, script_path):
        called.update(target_dt=target_dt, task_name=task_name, script_path=script_path)
        return task_name

    monkeypatch.setattr(rm, "_schedule_linux", fake_schedule)
    date, time_ = _future()

    class FakePlayer:
        def __init__(self):
            self.logs = []
        def write_log(self, msg):
            self.logs.append(msg)

    player = FakePlayer()
    result = rm.reminder({"date": date, "time": time_, "message": "Kaffee kochen"}, player=player)
    assert result.startswith("Reminder set for ")
    assert called["script_path"].exists()
    assert player.logs and "Kaffee kochen" in player.logs[0]


def test_reminder_dispatches_to_the_right_os_scheduler(monkeypatch):
    seen = []
    monkeypatch.setattr(rm, "_get_os", lambda: "mac")
    monkeypatch.setattr(rm, "_schedule_mac", lambda *a, **k: seen.append("mac") or "job")
    monkeypatch.setattr(rm, "_schedule_windows", lambda *a, **k: seen.append("windows") or "job")
    monkeypatch.setattr(rm, "_schedule_linux", lambda *a, **k: seen.append("linux") or "job")
    date, time_ = _future()
    rm.reminder({"date": date, "time": time_, "message": "x"})
    assert seen == ["mac"]


def test_reminder_reports_failure_when_scheduler_returns_no_job_id(monkeypatch):
    monkeypatch.setattr(rm, "_get_os", lambda: "linux")
    monkeypatch.setattr(rm, "_schedule_linux", lambda *a, **k: "")
    date, time_ = _future()
    result = rm.reminder({"date": date, "time": time_, "message": "x"})
    assert "couldn't register" in result


def test_reminder_handles_script_writing_failure(monkeypatch):
    monkeypatch.setattr(rm, "_write_notify_script", lambda *a, **k: (_ for _ in ()).throw(OSError("Diskvoll")))
    date, time_ = _future()
    result = rm.reminder({"date": date, "time": time_, "message": "x"})
    assert "Could not prepare the reminder script" in result
    assert "Diskvoll" in result


def test_reminder_cleans_up_script_when_scheduling_raises(monkeypatch):
    monkeypatch.setattr(rm, "_get_os", lambda: "linux")

    def boom(*a, **k):
        raise RuntimeError("Scheduler explodiert")

    monkeypatch.setattr(rm, "_schedule_linux", boom)
    date, time_ = _future()
    result = rm.reminder({"date": date, "time": time_, "message": "x"})
    assert "Something went wrong" in result
    # the script that was written before scheduling failed must be cleaned up
    assert list(rm._scripts_dir().glob("MIAReminder_*.py")) == []


def test_tool_declaration_shape():
    assert rm.TOOL["name"] == "reminder"
    assert rm.TOOL["handler"] is rm.reminder
    assert set(rm.TOOL["parameters"]["required"]) == {"date", "time", "message"}
